# Site settings
author: John Hayes
title: John Hayes's Blog
header-img: img/home-bg.png
email: johnnyhayes7@gmail.com
copyright_name: John Hayes
description: > # this means to ignore newlines until "baseurl:"
  Loops
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  JohnHayes7

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
